"""create data_records table

Revision ID: 31a362a46939
Revises: ea7404b2f261
Create Date: 2026-08-29 13:14:06.539429

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '31a362a46939'
down_revision: str | None = 'ea7404b2f261'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'IMPORT', 'REALTIME', name='data_source'), server_default='MANUAL', nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_records_category_timestamp', 'data_records', ['category', 'timestamp'], unique=False)
    op.create_index('ix_data_records_source_timestamp', 'data_records', ['source', 'timestamp'], unique=False)
    op.create_index('ix_data_records_timestamp', 'data_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_records_timestamp', table_name='data_records')
    op.drop_index('ix_data_records_source_timestamp', table_name='data_records')
    op.drop_index('ix_data_records_category_timestamp', table_name='data_records')
    op.drop_table('data_records')
    # ### end Alembic commands ###
