import math
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.data_record import DataSource


class SortableField(str, Enum):
    """Columns a client may sort on. Anything else is rejected by validation."""

    TIMESTAMP = "timestamp"
    VALUE = "value"
    TITLE = "title"
    CATEGORY = "category"
    CREATED_AT = "created_at"
    ID = "id"


class SortOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


def _reject_non_finite(value: float) -> float:
    if math.isnan(value) or math.isinf(value):
        raise ValueError("value must be a finite number")
    return value


class DataRecordCreate(BaseModel):
    """Client-supplied fields for a new record.

    `owner_id` and `is_anomaly` are absent by design: ownership comes from the
    authenticated user and anomaly marking is decided by the server.
    """

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1, max_length=200)
    value: float
    category: str = Field(min_length=1, max_length=100)
    timestamp: datetime
    source: DataSource = DataSource.MANUAL

    @field_validator("title", "category")
    @classmethod
    def strip_text(cls, text: str) -> str:
        stripped = text.strip()
        if not stripped:
            raise ValueError("must not be blank")
        return stripped

    @field_validator("value")
    @classmethod
    def finite_value(cls, value: float) -> float:
        return _reject_non_finite(value)

    @field_validator("source")
    @classmethod
    def reject_generated_source(cls, source: DataSource) -> DataSource:
        if source is DataSource.REALTIME:
            raise ValueError("REALTIME records are generated by the system")
        return source


class DataRecordUpdate(BaseModel):
    """Partial update. Every field is optional; `source` is immutable."""

    model_config = ConfigDict(extra="forbid")

    title: str | None = Field(default=None, min_length=1, max_length=200)
    value: float | None = None
    category: str | None = Field(default=None, min_length=1, max_length=100)
    timestamp: datetime | None = None

    @field_validator("title", "category")
    @classmethod
    def strip_text(cls, text: str | None) -> str | None:
        if text is None:
            return None
        stripped = text.strip()
        if not stripped:
            raise ValueError("must not be blank")
        return stripped

    @field_validator("value")
    @classmethod
    def finite_value(cls, value: float | None) -> float | None:
        return None if value is None else _reject_non_finite(value)


class DataRecordRead(BaseModel):
    """Full record representation returned to clients."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    value: float
    category: str
    timestamp: datetime
    source: DataSource
    is_anomaly: bool
    owner_id: int | None
    created_at: datetime
    updated_at: datetime


class DataRecordPage(BaseModel):
    """One page of records plus the metadata needed to navigate the rest."""

    items: list[DataRecordRead]
    total: int
    page: int
    page_size: int
    pages: int
